files: service/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: name-tests-test
        args: [--django]
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          [service/]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [service/]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [-r, service/]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8 # E***, W***, F***
        args: [service/]
        additional_dependencies:
          - dlint # DUO***
          - flake8-2020 # YTT***
          - flake8-bugbear # B***
          - flake8-builtins # A***
          - flake8-comprehensions # C4**
          - flake8-deprecated # D***
          - flake8-variables-names # VNE***
          - mccabe # C9**
          - pep8-naming # N8**