repos:
  - repo: local
    hooks:
      - id: CI
        name: run Sh CI script
        entry: bash conf/pre-commit/precommit.sh
        language: system
        types: [python]
        stages: [commit]
