version: "3.9"

services:
  nginx:
    image: nginx:1.19.8-alpine
    volumes:
      - ./config/nginx-conf.d:/etc/nginx/conf.d:ro
      - static_volume:/var/www/html/static
    ports:
      - 80:80
    depends_on:
      - task_api

  task_api:
    build: .
    command: gunicorn -c config/gunicorn.py
    env_file:
      - config/env/.prod-env
    volumes:
      - static_volume:/code/staticfiles
    depends_on:
      - db

  db:
    image: postgres:14.0
    ports:
      - 5432
    env_file:
      - config/env/.prod-env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - 6379

volumes:
  postgres_data:
  static_volume:
