version: "3.9"

services:

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - conf/env/.dev-env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:

