version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/html/static
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build:
      context: .
    command: >
      bash -c "
        python manage.py collectstatic --no-input && 
        gunicorn -c config/gunicorn.py
      "
    volumes:
      - static_volume:/code/staticfiles
      - ./config/prod_env/:/code/django_configs:ro
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - service/django_configs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis

volumes:
  postgres_data:
  static_volume:
