version: '3.9'

services:
  nginx:
    image: nginx:1.19.8-alpine
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d:ro
      - static_volume:/var/www/html/static
    ports:
      - 3000:80
    depends_on:
      - task_api

  task_api:
    build: .
    command: gunicorn -c conf/gunicorn.py
    environment:
      - DEBUG=false
    env_file:
      - conf/env/.prod-env
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:14.0
    ports:
      - 5432
    env_file:
      - conf/env/.prod-env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
    ports:
      - 6379

volumes:
  postgres_data:
  static_volume:
