version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume_test:/var/www/html/static
    ports:
      - 80:80
    networks:
      - django_test_network
    depends_on:
      - api

  api:
    build:
      context: .
    command: >
      bash -c "
        python manage.py makemigrations && 
        python manage.py migrate
        python manage.py collectstatic --no-input && 
        python manage.py generate_test_data && 
        gunicorn -c config/gunicorn.py
      "
    links:
      - db:db
    networks:
      - django_test_network
    volumes:
      - static_volume_test:/code/staticfiles
      - ./config/prod_env/:/code/django_configs:ro
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - ./config/prod_env/.env
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    networks:
      - django_test_network

  redis:
    image: redis
    networks:
      - django_test_network

volumes:
  postgres_data_test:
  static_volume_test:


networks:
  django_test_network:
    driver: bridge
