# Generated by Django 3.2.7 on 2021-09-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list",
            name="is_active",
        ),
    ]
